<a href="https://colab.research.google.com/github/T3widianto22/T3widianto22/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files
filennya = files.upload()

Saving AnyConv.com__REKAP TAGIHAN TJW 2022 NEW  (7).csv to AnyConv.com__REKAP TAGIHAN TJW 2022 NEW  (7).csv

In [ ]:
filennya

{'AnyConv.com__REKAP TAGIHAN TJW 2022 NEW  (7).csv': b',PT TRITAMA JAYA WISATA,,,,,,,,,,,,,,,,,,\n,REKAP TAGIHAN PER JANUARI 2022,,,,,,,,,,,,,,,,,,\n,,,,,,,,,,,,,,,,,,,\nCustomer Code,NO INVOICE,Customer Name,Attention To,Date,Due Date, SELL, Outstanding, BASIC PRICE, CN, PAJAK 1%, PROFIT,Passenger,FLIGHT,Ticket,VENDOR,BANK,Tgl Pembayaran, Jumlah ,\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,211,100.00 ",," 920,300.00 "," 50,000.00 "," 12,111.00 "," 228,689.00 ",TUNGGONO AGUS MR,LION AIR,CGK SUB ID 12JAN22,ANNISA TRAVEL,MANDIRI,26-Feb-22," 11,214,800.00 ",\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,211,100.00 ",," 920,300.00 "," 50,000.00 "," 12,111.00 "," 228,689.00 ",SUHANTA MR,LION AIR,CGK SUB ID 12JAN22,ANNISA TRAVEL,,,,\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,211,100.00 ",," 920,300.00 "," 50,000.00 "," 12,111.00 "," 228,689.00 ",SUSETYO BOWO MR,LION AIR,CGK SUB ID 12JAN22,ANNISA TRAVEL,,,,\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,211,100.00 ",," 920,300.00 "," 50,000.00 "," 12,111.00 "," 228,689.00 ",MADJID HASRAN MR,LION AIR,CGK SUB ID 12JAN22,ANNISA TRAVEL,,,,\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,592,600.00 ",," 1,331,900.00 "," 50,000.00 "," 15,926.00 "," 194,774.00 ",TUNGGONO AGUS MR,LION AIR,SUB CGK ID 13JAN22,ANNISA TRAVEL,,,,\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,592,600.00 ",," 1,331,900.00 "," 50,000.00 "," 15,926.00 "," 194,774.00 ",SUHANTA MR,LION AIR,SUB CGK ID 13JAN22,ANNISA TRAVEL,,,,\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,592,600.00 ",," 1,331,900.00 "," 50,000.00 "," 15,926.00 "," 194,774.00 ",SUSETYO BOWO MR,LION AIR,SUB CGK ID 13JAN22,ANNISA TRAVEL,,,,\n,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22," 1,592,600.00 ",," 1,331,900.00 "," 50,000.00 "," 15,926.00 "," 194,774.00 ",MADJID HASRAN MR,LION AIR,SUB CGK ID 13JAN22,ANNISA TRAVEL,,,,\n,HOTJW-31026,KRAKATAU STEEL,CHINTYA MRS,19-Jan-22,3-Feb-22," 14,689,800.00 ",," 14,170,100.00 ",," 146,898.00 "," 372,802.00 ",KARIM SILMY MR,GARUDA INDONESIA,CGK DPS CGK GA 19JAN22 ,JENDELA,BRI,10-Feb-22," 14,689,800.00 ",\n,HOTJW-31027,KEMENTERIAN PERINDUSTRIAN,ARIF MR,18-Jan-22,2-Feb-22," 1,598,000.00 ",," 1,298,743.33 "," 50,000.00 "," 15,980.00 "," 233,276.67 ",ARIF SURYANA MR,CITILINK,CGK UPG QG 15 JAN22,MNC,BRI,14-Feb-22," 4,794,000.00 ",\n,HOTJW-31027,KEMENTERIAN PERINDUSTRIAN,ARIF MR,18-Jan-22,2-Feb-22," 1,598,000.00 ",," 1,298,743.33 "," 50,000.00 "," 15,980.00 "," 233,276.67 ",AARIEF RAKHMAN HADI MR,CITILINK,CGK UPG QG 15 JAN22,MNC,,,,\n,HOTJW-31027,KEMENTERIAN PERINDUSTRIAN,ARIF MR,18-Jan-22,2-Feb-22," 1,598,000.00 ",," 1,298,743.33 "," 50,000.00 "," 15,980.00 "," 233,276.67 ",TRI YUNADI MR,CITILINK,CGK UPG QG 15 JAN22,MNC,,,,\n,00004,KEMENTERIAN PERDAGANGAN,WIDYA MRS,16-Jan-22,31-Jan-22," 4,268,000.00 ",," 4,126,600.00 ",," 42,680.00 "," 98,720.00 ",DYAH EKOWATI MRS,GARUDA INDONESIA,CGKUPGCGK GA  20JAN22,JENDELA,MANDIRI,10-Feb-22," 4,268,000.00 ",\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 6,850,000.00 ",," 6,104,800.00 "," 50,000.00 "," 68,500.00 "," 626,700.00 ",MURSALI HAFIDZ MR,LION AIR,CGK TNJ ID 24JAN22,AMBASADOR LION,BRI,11-Feb-22," 23,977,000.00 ",\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 6,850,000.00 ",," 6,104,800.00 "," 50,000.00 "," 68,500.00 "," 626,700.00 ",SUSETYO BOWO MR,LION AIR,CGK TNJ ID 24JAN22,AMBASADOR LION,,,,\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 1,699,800.00 ",," 1,074,800.00 "," 50,000.00 "," 16,998.00 "," 558,002.00 ",YUNADI TRI MR,WINGS AIR,CGK BTH IU 24JAN 22,MNC,,,,\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 1,699,800.00 ",," 1,486,550.00 "," 50,000.00 "," 16,998.00 "," 146,252.00 ",ANGGALAYA RUBBY MR,WINGS AIR,CGK BTH IU 24JAN 22,MNC,,,,\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 1,719,500.00 ",," 1,486,550.00 "," 50,000.00 "," 17,195.00 "," 165,755.00 ",MURSALI HAFIDZ MR,CITILINK,BTH CGK QG 26JAN22,MNC,,,,\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 1,719,500.00 ",," 1,486,550.00 "," 50,000.00 "," 17,195.00 "," 165,755.00 ",SUSETYO BOWO MR,CITILINK,BTH CGK QG 26JAN22,MNC,,,,\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 1,719,500.00 ",," 1,486,550.00 "," 50,000.00 "," 17,195.00 "," 165,755.00 ",YUNADI TRI MR,CITILINK,BTH CGK QG 26JAN22,MNC,,,,\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 1,719,500.00 ",," 1,486,550.00 "," 50,000.00 "," 17,195.00 "," 165,755.00 ",ANGGALAYA RUBBY MR,CITILINK,BTH CGK QG 26JAN22,MNC,,,,\n,00005,KEMENTERIAN PERINDUSTRIAN,BOWO MR,26-Jan-22,10-Feb-22," 1,719,500.00 ",," 1,373,200.00 "," 50,000.00 "," 17,195.00 "," 279,105.00 ",ROHIMAT NURBAYA MR,CITILINK,BTH CGK QG 26JAN22,MNC,BRI,11-Feb-22," 1,719,500.00 ",\n,00006,KEMENTERIAN PERINDUSTRIAN,PASTIAH MRS,16-Jan-22,31-Jan-22, -   ,," 848,170.00 ",, -   ,"-848,170.00 ",PASTIAH MRS,GARUDA INDONESIA,TKG CGK GA 16JAN22,JENDELA,ENTERTAINT,ENTERTAINT,,\n,00006,KEMENTERIAN PERINDUSTRIAN,PASTIAH MRS,16-Jan-22,31-Jan-22, -   ,," 848,170.00 ",, -   ,"-848,170.00 ",OKTIA YETI MRS,GARUDA INDONESIA,TKG CGK GA 16JAN22,JENDELA,ENTERTAINT,ENTERTAINT,,\n,00007,KEMENTERIAN PERINDUSTRIAN,NOVAN DITTO MR,16-Jan-22,31-Jan-22," 2,808,400.00 ",," 2,742,190.00 ",," 28,084.00 "," 38,126.00 ",NOVAN DITTO MR,GARUDA INDONESIA,CGK SUB CGK 26 JAN22,MNC,BRI,1-Mar-22," 5,592,400.00 ",\n,00008,KEMENTERIAN PERINDUSTRIAN,SIGIT HARIYONO MR,16-Jan-22,31-Jan-22," 1,418,700.00 ",," 1,385,740.00 ",," 14,187.00 "," 18,773.00 ",SIGIT HARIYONO MR,GARUDA INDONESIA,CGK SUB,MNC,,,,\n,00008,KEMENTERIAN PERINDUSTRIAN,SIGIT HARIYONO MR,31-Jan-22,15-Feb-22," 1,365,300.00 ",," 1,167,800.00 ",," 13,653.00 "," 183,847.00 ",SIGIT HARIYONO MR,CITILINK,,MNC,,,,\n,00009,KEMENTERIAN PERINDUSTRIAN,PASTIAH MRS,16-Jan-22,31-Jan-22," 3,408,200.00 ",," 3,298,720.00 ",," 34,082.00 "," 75,398.00 ",PASTIAH MRS,GARUDA INDONESIA,CGK-DPS-CGK 26JAN22,JENDELA,BRI,2-Feb-22," 16,198,200.00 ",\n,00009,KEMENTERIAN PERINDUSTRIAN,PASTIAH MRS,16-Jan-22,31-Jan-22," 3,408,200.00 ",," 3,298,720.00 ",," 34,082.00 "," 75,398.00 ",PUTRI FARAH FADILAH MRS,GARUDA INDONESIA,CGK-DPS-CGK 26JAN22,JENDELA,,,,\n,00009,KEMENTERIAN PERINDUSTRIAN,PASTIAH MRS,16-Jan-22,31-Jan-22," 3,408,200.00 ",," 3,298,720.00 ",," 34,082.00 "," 75,398.00 ",SIREGAR IQBAL DERMAWAN MR,GARUDA INDONESIA,CGK-DPS-CGK 26JAN22,JENDELA,,,,\n,00010,KEMENTERIAN PERINDUSTRIAN,ESTI MRS,16-Jan-22,31-Jan-22," 1,991,200.00 ",," 1,932,520.00 ",," 19,912.00 "," 38,768.00 ",APRILIANI ILSA MRS,GARUDA INDONESIA,CGK-SRG-CGK 20JAN22,JENDELA,,,,\n,00010,KEMENTERIAN PERINDUSTRIAN,ESTI MRS,16-Jan-22,31-Jan-22," 1,991,200.00 ",," 1,932,520.00 ",," 19,912.00 "," 38,768.00 ",PANGESTUTI ESTI MRS,GARUDA INDONESIA,CGK-SRG-CGK 20JAN22,JENDELA,,,,\n,00010,KEMENTERIAN PERINDUSTRIAN,ESTI MRS,16-Jan-22,31-Jan-22," 1,991,200.00 ",," 1,932,520.00 ",," 19,912.00 "," 38,768.00 ",RINAYANTI MRS,GARUDA INDONESIA,CGK-SRG-CGK 20JAN22,JENDELA,,,,\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 1,010,600.00 ",," 983,760.00 ",," 10,106.00 "," 16,734.00 ",SUSETYO BOWO MR,GARUDA INDONESIA,CGK-SRG 28JAN22,JENDELA,BRI,9-Mar-22," 7,565,600.00 ",\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 1,010,600.00 ",," 983,760.00 ",," 10,106.00 "," 16,734.00 ",SUHANTA MR,GARUDA INDONESIA,CGK-SRG 28JAN22,JENDELA,,,,\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 1,010,600.00 ",," 983,760.00 ",," 10,106.00 "," 16,734.00 ",BAYU KURNIAWAN MR,GARUDA INDONESIA,CGK-SRG 28JAN22,JENDELA,,,,\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 1,010,600.00 ",," 983,760.00 ",," 10,106.00 "," 16,734.00 ",ARIF SURYANA MR,GARUDA INDONESIA,CGK-SRG 28JAN22,JENDELA,,,,\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 880,800.00 ",," 619,000.00 "," 50,000.00 "," 8,808.00 "," 202,992.00 ",SUSETYO BOWO MR,LION AIR,SRG-CGK 30JAN22,MNC,,,,\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 880,800.00 ",," 619,000.00 "," 50,000.00 "," 8,808.00 "," 202,992.00 ",SUHANTA MR,LION AIR,SRG-CGK 30JAN22,MNC,,,,\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 880,800.00 ",," 619,000.00 "," 50,000.00 "," 8,808.00 "," 202,992.00 ",BAYU KURNIAWAN MR,LION AIR,SRG-CGK 30JAN22,MNC,,,,\n,00011,KEMENTERIAN PERINDUSTRIAN,BOWO MR,27-Jan-22,11-Feb-22," 880,800.00 ",," 619,000.00 "," 50,000.00 "," 8,808.00 "," 202,992.00 ",ARIF SURYANA MR,LION AIR,SRG-CGK 30JAN22,MNC,,,,\n,00012,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 1,067,800.00 ",," 1,044,219.00 ",," 10,678.00 "," 12,903.00 ",RIZKA AZHARI,GARUDA INDONESIA,CGK YIA,MNC,BRI,8-Feb-22," 8,459,400.00 ",\n,00012,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 1,067,800.00 ",," 1,044,219.00 ",," 10,678.00 "," 12,903.00 ",BABY MEDINA,GARUDA INDONESIA,CGK YIA,MNC,,,,\n,00012,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 1,067,800.00 ",," 1,044,219.00 ",," 10,678.00 "," 12,903.00 ",NI MADE AYU,GARUDA INDONESIA,CGK YIA,MNC,,,,\n,00012,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 1,752,000.00 ",," 1,300,900.00 ",," 17,520.00 "," 433,580.00 ",RIZKA AZHARI,CITILINK,YIA CGK,MNC,,,,\n,00012,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 1,752,000.00 ",," 1,300,900.00 ",," 17,520.00 "," 433,580.00 ",BABY MEDINA,CITILINK,YIA CGK,MNC,,,,\n,00012,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 1,752,000.00 ",," 1,300,900.00 ",," 17,520.00 "," 433,580.00 ",NI MADE AYU,CITILINK,YIA CGK,MNC,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 3,000,500.00 ",," 2,901,300.00 ",," 30,005.00 "," 69,195.00 ",KAMA ADYTIA,GARUDA INDONESIA,CGK-MDC 21JAN22,JENDELA,BRI,10-Mar-22," 24,318,500.00 ",\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 3,000,500.00 ",," 2,901,300.00 ",," 30,005.00 "," 69,195.00 ",ADINDA BIDARI,GARUDA INDONESIA,CGK-MDC 21JAN22,JENDELA,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 3,000,500.00 ",," 2,901,300.00 ",," 30,005.00 "," 69,195.00 ",BOBSI TUA,GARUDA INDONESIA,CGK-MDC 21JAN22,JENDELA,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 3,000,500.00 ",," 2,901,300.00 ",," 30,005.00 "," 69,195.00 ",HARI AGUNG,GARUDA INDONESIA,CGK-MDC 21JAN22,JENDELA,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22,,,,,,,MAROLOP NAINGGOLAN MR,GARUDA INDONESIA,CGK-MDC 21JAN22,JENDELA,,,,REREOUTE BALI\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 3,000,500.00 ",," 2,901,300.00 ",," 30,005.00 "," 69,195.00 ",PANJAITAN SILVANA MRS,GARUDA INDONESIA,CGK-MDC 21JAN22,JENDELA,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 2,930,500.00 ",," 2,854,563.00 ",," 29,305.00 "," 46,632.00 ",HARI AGUNG,GARUDA INDONESIA,MDC CGK 23JAN22,MNC,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 2,128,500.00 ",," 1,880,300.00 ",," 21,285.00 "," 226,915.00 ",KAMA ADYTIA,LION AIR,MDC CGK,MNC,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 2,128,500.00 ",," 1,880,300.00 ",," 21,285.00 "," 226,915.00 ",ADINDA BIDARI,LION AIR,MDC CGK,MNC,,,,\n,00013,KEMENTERIAN PERDAGANGAN,ADIT MR,16-Jan-22,31-Jan-22," 2,128,500.00 ",," 1,880,300.00 ",," 21,285.00 "," 226,915.00 ",BOBSI TUA,LION AIR,MDC CGK,MNC,,,,\n,00014,PT TIJARAH BERKAH MULIA,ARDIZA DWI,16-Jan-22,31-Jan-22," 787,060.00 ",," 787,060.00 ",," 7,870.60 ","-7,870.60 ",ARDIZA DWI,CITILINK,CGK BWX,MNC,Top up MNC,Top up MNC," 787,060.00 ",\n,00015,KEMENTERIAN PERDAGANGAN,IREN MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 988,548.00 ",," 10,106.00 "," 11,946.00 ",PANGESTI IRENA MRS,GA,CGK SRG 01FEB22,MNC,BRI,4-Feb-22," 3,971,800.00 ",\n,00015,KEMENTERIAN PERDAGANGAN,IREN MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 988,548.00 ",," 10,106.00 "," 11,946.00 ",HANSYAH BUDI MR,GA,CGK SRG 01FEB22,MNC,,,,\n,00015,KEMENTERIAN PERDAGANGAN,IREN MRS,31-Jan-22,15-Feb-22," 975,300.00 ",," 627,800.00 ",," 9,753.00 "," 337,747.00 ",PANGESTI IRENA MRS,CITILINK,SRG CGK 04FEB22,MNC,,,,\n,00015,KEMENTERIAN PERDAGANGAN,IREN MRS,31-Jan-22,15-Feb-22," 975,300.00 ",," 627,800.00 ",," 9,753.00 "," 337,747.00 ",HANSYAH BUDI MR,CITILINK,SRG CGK 04FEB22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Syahresmita,GA,CGK SRG 3 FEB 22,MNC,BRI,15-Feb-22," 20,000,000.00 ",\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Emma Natalia,GA,CGK SRG 3 FEB 22,MNC,BRI,15-Feb-22," 10,000,000.00 ",\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Renti Montiska,GA,CGK SRG 3 FEB 22,MNC,BRI,15-Feb-22," 6,995,400.00 ",\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Anjar Ramdhana,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Raisa Savitri Ramadhani,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Damayanti Simangunsong,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Aryo Cahyo Tranggono,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Aktivania Ashlah,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Akhyar Yohanda,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Pastiah,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Ilsa Apriliani,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Atik,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Ridhatul Akbar,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Clara Beatrix,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Agung Ashshiddiqi,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Farah Fadhilah Putri,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Dimas Prasetyo,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Hasti Nuhrin,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,010,600.00 ",," 986,720.00 ",," 10,106.00 "," 13,774.00 ",Aryo Yuwono,GA,CGK SRG 3 FEB 22,MNC,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 729,000.00 ",," 704,300.00 ",," 7,290.00 "," 17,410.00 ",PRASETYO DIMAS MR,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 659,300.00 ",," 8,990.00 "," 230,710.00 ",RINAYANTI RINAYANTI,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 659,300.00 ",," 8,990.00 "," 230,710.00 ",PUTRI FARAH FADHILAH MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 645,300.00 ",," 8,990.00 "," 244,710.00 ",ASHSHIDDIQI AGUNG MR,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 617,000.00 ",," 8,990.00 "," 273,010.00 ",NATALIA EMMA MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 617,000.00 ",," 8,990.00 "," 273,010.00 ",MONTISKA RENTI MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 602,000.00 ",," 8,990.00 "," 288,010.00 ",SIMANGUNSONG DAMAYANTI MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 602,000.00 ",," 8,990.00 "," 288,010.00 ",PASTIAH PASTIAH MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,179,000.00 ",," 871,000.00 ",," 11,790.00 "," 296,210.00 ",SYAHRESMITA SYAHRESMITA MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,179,000.00 ",," 617,000.00 ",," 11,790.00 "," 550,210.00 ",RAMADHANA ANJAR MR,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,179,000.00 ",," 871,000.00 ",," 11,790.00 "," 296,210.00 ",APRILLIANI ILSA MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,179,000.00 ",," 913,300.00 ",," 11,790.00 "," 253,910.00 ",ATIK ATIK MR,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,179,000.00 ",," 913,300.00 ",," 11,790.00 "," 253,910.00 ",HUTAPEA CLARA BEATRIX MS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 602,000.00 ",," 8,990.00 "," 288,010.00 ",ASHLAH AKTIVANIA MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 899,000.00 ",," 659,300.00 ",," 8,990.00 "," 230,710.00 ",AKBAR RIDHATUL MR,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 950,000.00 ",," 659,300.00 ",," 9,500.00 "," 281,200.00 ",TRANGGONO ARYO CAHYO MR,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 950,000.00 ",," 704,300.00 ",," 9,500.00 "," 236,200.00 ",NUHRIN HASTI MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,HOTJW-31011,KEMENTERIAN PERINDUSTRIAN,HASTI MRS,31-Jan-22,15-Feb-22," 1,179,000.00 ",," 871,000.00 ",," 11,790.00 "," 296,210.00 ",RAMADHANI RAISA SAVITRI MRS,LION AIR,SRG CGK 05FEB22,,,,,\n,,,,,,,,,,,,,,,,,,,\n,,GRAND TOTAL,,,," 164,552,060.00 ", -   ," 147,981,366.00 "," 1,200,000.00 "," 1,645,520.60 "," 13,725,173.40 ",,,,,,," 164,551,460.00 ",\n,,,,,,,,,,,,,,,,,,,\n,,PENJUALAN," 164,552,060.00 ",,,,,,,,,,,,,,,,\n,,BASIC FARE," 147,981,366.00 ",,,,,,,,,,,,,,,,\n,,CN," 1,200,000.00 ",,,,,,,,,,,,,,,,\n,,PAJAK," 1,645,520.60 ",,,,,,,,,,,,,,,,\n,,PROFIT," 13,725,173.40 ",,,,,,,,,,,,,,,,\n,,,,,,,,,,,,,,,,,,,\n,,OUTSTANDING JANUARI 2022, -   ,,,,,,,,,,,,,,,,\n,,PEMASUKAN," 164,552,060.00 ",,,,,,,,,,,,,,,,\n,,ENTERTAIN , 600.00 ,,,,,,,,,,,,,,,,\n,,JUMLAH PEMASUKAN," 164,551,460.00 ",,,,,,,,,,,,,,,,\n'}

In [ ]:
import io
df = pd.read_csv(io.StringIO(filennya['AnyConv.com__REKAP TAGIHAN TJW 2022 NEW  (7).csv'].decode('utf-8')))
print(df)

        Unnamed: 0          PT TRITAMA JAYA WISATA                 Unnamed: 2  \
0              NaN  REKAP TAGIHAN PER JANUARI 2022                        NaN
1              NaN                             NaN                        NaN
2    Customer Code                      NO INVOICE              Customer Name
3              NaN                     HOTJW-31025  KEMENTERIAN PERINDUSTRIAN
4              NaN                     HOTJW-31025  KEMENTERIAN PERINDUSTRIAN
..             ...                             ...                        ...
110            NaN                             NaN                        NaN
111            NaN                             NaN   OUTSTANDING JANUARI 2022
112            NaN                             NaN                  PEMASUKAN
113            NaN                             NaN                 ENTERTAIN
114            NaN                             NaN           JUMLAH PEMASUKAN

           Unnamed: 3 Unnamed: 4 Unnamed: 5      Unnamed: 6    Unnamed: 7  \
0                 NaN        NaN        NaN             NaN           NaN
1                 NaN        NaN        NaN             NaN           NaN
2        Attention To       Date   Due Date            SELL   Outstanding
3             BOWO MR  12-Jan-22  27-Jan-22   1,211,100.00            NaN
4             BOWO MR  12-Jan-22  27-Jan-22   1,211,100.00            NaN
..                ...        ...        ...             ...           ...
110               NaN        NaN        NaN             NaN           NaN
111              -           NaN        NaN             NaN           NaN
112   164,552,060.00         NaN        NaN             NaN           NaN
113           600.00         NaN        NaN             NaN           NaN
114   164,551,460.00         NaN        NaN             NaN           NaN

       Unnamed: 8   Unnamed: 9  Unnamed: 10   Unnamed: 11       Unnamed: 12  \
0             NaN          NaN          NaN           NaN               NaN
1             NaN          NaN          NaN           NaN               NaN
2     BASIC PRICE           CN     PAJAK 1%        PROFIT         Passenger
3     920,300.00    50,000.00    12,111.00    228,689.00   TUNGGONO AGUS MR
4     920,300.00    50,000.00    12,111.00    228,689.00         SUHANTA MR
..            ...          ...          ...           ...               ...
110           NaN          NaN          NaN           NaN               NaN
111           NaN          NaN          NaN           NaN               NaN
112           NaN          NaN          NaN           NaN               NaN
113           NaN          NaN          NaN           NaN               NaN
114           NaN          NaN          NaN           NaN               NaN

    Unnamed: 13         Unnamed: 14    Unnamed: 15 Unnamed: 16  \
0           NaN                 NaN            NaN         NaN
1           NaN                 NaN            NaN         NaN
2        FLIGHT              Ticket         VENDOR        BANK
3      LION AIR  CGK SUB ID 12JAN22  ANNISA TRAVEL     MANDIRI
4      LION AIR  CGK SUB ID 12JAN22  ANNISA TRAVEL         NaN
..          ...                 ...            ...         ...
110         NaN                 NaN            NaN         NaN
111         NaN                 NaN            NaN         NaN
112         NaN                 NaN            NaN         NaN
113         NaN                 NaN            NaN         NaN
114         NaN                 NaN            NaN         NaN

        Unnamed: 17      Unnamed: 18 Unnamed: 19
0               NaN              NaN         NaN
1               NaN              NaN         NaN
2    Tgl Pembayaran          Jumlah          NaN
3         26-Feb-22   11,214,800.00          NaN
4               NaN              NaN         NaN
..              ...              ...         ...
110             NaN              NaN         NaN
111             NaN              NaN         NaN
112             NaN              NaN         NaN
113             NaN              NaN         NaN
114             NaN              NaN         NaN

[115 rows x 20 columns]

In [ ]:
df.head()

,Unnamed: 0,PT TRITAMA JAYA WISATA,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,REKAP TAGIHAN PER JANUARI 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Customer Code,NO INVOICE,Customer Name,Attention To,Date,Due Date,SELL,Outstanding,BASIC PRICE,CN,PAJAK 1%,PROFIT,Passenger,FLIGHT,Ticket,VENDOR,BANK,Tgl Pembayaran,Jumlah,NaN
3,NaN,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22,"1,211,100.00",NaN,"920,300.00","50,000.00","12,111.00","228,689.00",TUNGGONO AGUS MR,LION AIR,CGK SUB ID 12JAN22,ANNISA TRAVEL,MANDIRI,26-Feb-22,"11,214,800.00",NaN
4,NaN,HOTJW-31025,KEMENTERIAN PERINDUSTRIAN,BOWO MR,12-Jan-22,27-Jan-22,"1,211,100.00",NaN,"920,300.00","50,000.00","12,111.00","228,689.00",SUHANTA MR,LION AIR,CGK SUB ID 12JAN22,ANNISA TRAVEL,NaN,NaN,NaN,NaN